name: Deploy to GitHub Pages  
# event is a trigger for a workflow our event is specified to happen on a push to the main branch once this happens it`s going to run all the jobs within the workflow
on:
  push:
    branches:
      - main  # self explanatory 

jobs:
  build:
    name: Build Docusaurus  
    runs-on: ubuntu-latest # we specify our runner here (container that will run our code) 
    steps:
      - uses: actions/checkout@v4 # check out the repository under the GitHub Actions runner /  allows the workflow to access the repository's contents.
        with:
          fetch-depth: 0 # ensures that the entire git history is fetched

      - uses: actions/setup-node@v4 # setup nodeJS env
        with:
          node-version: 18
          cache: npm # enables caching of npm dependencies

      - name: Install dependencies  
        run: npm ci # installs project dependencies based on package-lock.json
      
      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3 # uploads the build directory as an artifact
        with:
          path: build # specifies the path to the build directory


  deploy:
    name: Deploy to GitHub Pages
    needs: build # depends on build job to complete before starting

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # dynamically sets the URL of the deployed site

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # deploys the build artifacts to GitHub Pages